import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/Query/query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <Navbar />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
